version: 2.1
executors:
  ruby_executor:
    docker:
      - image: cimg/ruby:<<parameters.version>>
    parameters:
      version:
        type: string
        default: "3.1"
jobs:
  build_and_test:
    executor:
      name: ruby_executor
      version: <<parameters.ruby_version>>
    parameters:
      ruby_version:
        type: string
    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            gem install bundler
            bundle install
            bundle exec rake
workflows:
  build_and_test:
    jobs:
      - build_and_test:
          name: build_and_test_ruby_3_1
          ruby_version: "3.1"
      - build_and_test:
          name: build_and_test_ruby_3_2
          ruby_version: "3.2"
      - build_and_test:
          name: build_and_test_ruby_3_3
          ruby_version: "3.3"
      - build_and_test:
          name: build_and_test_ruby_3_4
          ruby_version: "3.4"
